[tool.black]
line-length = 88
py36 = true
skip-numeric-underscore-normalization = true

[tool.tox]
legacy_tox_ini = """
[tox]
envlist=
  py34
  py35
  py36
  py37

[testenv]
deps=
  pytest
  requests_mock
commands=pytest
"""
