"""ccp_api - Cloud Commerce Pro API integration for Python."""

__title__ = "ccp_api"
__description__ = "Cloud Commerce Pro API integration for python."
__url__ = "http://github.com/lukeshiner/ccp_api.git"
__version__ = "0.0.1"
__release__ = "0.0.1"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
